FROM alpine:3.6

LABEL MAINTAINER="Aurelien PERRIER"

RUN apk --update add wget unzip curl php7

WORKDIR /srv/app

RUN wget --no-check-certificate https://wordpress.org/latest.zip
RUN unzip /srv/app/latest.zip -d /srv/app/ && \
        rm /srv/app/latest.zip

VOLUME ["/srv/app"]