FROM alpine:3.6

LABEL MAINTAINER="Aurelien PERRIER <perrie_a@etna-alternance.net>"

# Installing MySQL packages (MariaDB on alpine)
RUN apk --update add --no-cache mysql mysql-client && \
	addgroup mysql mysql

# Work path
WORKDIR /scripts

# Copy of the MySQL startup script
COPY ./scripts/start.sh ./start.sh
RUN chmod +x ./start.sh

# Creating the persistent volume
VOLUME [ "/var/lib/mysql" ]

EXPOSE 3306

ENTRYPOINT [ "./start.sh" ]