FROM alpine:3.6

LABEL maintainer="Aurelien PERRIER"
LABEL name="mysql"
LABEL location="Paris"

RUN apk update && \
	apk add mysql mysql-client && \
	addgroup mysql mysql && \
	mkdir /scripts && \
	rm -rf /var/cache/apk/*

VOLUME ["/var/lib/mysql"]

COPY ./scripts/startup.sh /scripts/startup.sh
RUN chmod +x /scripts/startup.sh

EXPOSE 3306

ENTRYPOINT ["./scripts/startup.sh"]