# For Swarm testing
version: '3'

services:
  wordpress:
    image: dockerimages_wordpress:latest
    container_name: wordpress
    env_file:
      - ./wordpress/.env
    volumes:
      - wordpress_data:/srv/app/wordpress

  telegraf:
    image: dockerimages_telegraf:latest
    container_name: telegraf
    env_file:
      - ./telegraf/.env
    volumes:
      - telegraf_data:/srv/app/telegraf
  
  influxdb:
    image: dockerimages_influxdb:latest
    container_name: influxdb
    env_file:
      - ./influxdb/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints: [node.type == logs]
    volumes:
      - influxdb_data:/var/lib/influxdb
      - telegraf_data:/root/telegraf
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8086:8086"
      - "8083:8083"

  grafana:
    image: dockerimages_grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints: [node.type == logs]
    volumes:
      - grafana_data:/grafana
      - telegraf_data:/root/telegraf
    ports:
      - "3000:3000"

  mysql:
    image: dockerimages_mysql:latest
    container_name: mysql
    env_file:
      - ./mysql/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.8'
          memory: 1024M
        reservations:
          cpus: '0.8'
          memory: 512M
      placement:
        constraints: [node.type == mysql]
    volumes:
      - db_data:/var/lib/mysql
      - telegraf_data:/root/telegraf
    ports:
      - "3306:3306"

  httpd:
    image: dockerimages_httpd:latest
    container_name: httpd
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.6'
          memory: 1024M
        reservations:
          cpus: '0.6'
          memory: 512M
      placement:
        constraints: [node.type == httpd]
    volumes:
      - wordpress_data:/var/www/localhost/htdocs
      - telegraf_data:/root/telegraf
    ports:
      - "80:80"

volumes:
  db_data: {}
  wordpress_data: {}
  telegraf_data: {}
  influxdb_data: {}
  grafana_data: {}