# For Swarm testing
version: '3'

services:
  minio:
    image: 172.16.231.6:5000/minio:0.1
    hostname: minio
    env_file:
      - ./minio/.env
    volumes:
      - minio_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      resources:
        limits:
          cpus: '5.000'
          memory: 100M
        reservations:
          cpus: '5.000'
          memory: 50M
      placement:
        constraints: [node.type == httpd]
    ports:
      - "9000:9000"

  wordpress:
    image: 172.16.231.6:5000/wordpress:0.1
    hostname: wordpress
    env_file:
      - ./wordpress/.env
    volumes:
      - wordpress_data:/srv/app/wordpress

  telegraf:
    image: 172.16.231.6:5000/telegraf:0.1
    hostname: telegraf
    env_file:
      - ./telegraf/.env
    volumes:
      - telegraf_data:/srv/app/telegraf
  
  influxdb:
    image: 172.16.231.6:5000/influxdb:0.1
    hostname: influxdb
    env_file:
      - ./influxdb/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 500M
        reservations:
          cpus: '10.000'
          memory: 500M
      placement:
        constraints: [node.type == master]
    volumes:
      - influxdb_data:/var/lib/influxdb
      - telegraf_data:/root/telegraf
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8086:8086"
      - "8083:8083"
  
  kapacitor:
    image: 172.16.231.6:5000/kapacitor:0.1
    hostname: kapacitor
    depends_on:
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.type == master]
    volumes:
      - kapacitor_data:/var/lib/kapacitor
    ports:
      - "9092:9092"

  chronograf:
    image: 172.16.231.6:5000/chronograf:0.1
    hostname: chronograf
    env_file:
      - ./chronograf/.env
    depends_on:
      - influxdb
      - kapacitor
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.type == master]
    volumes:
      - chronograf_data:/var/lib/chronograf
    ports:
      - "8888:8888"

  mysql:
    image: 172.16.231.6:5000/mysql:0.1
    hostname: mysql
    env_file:
      - ./mysql/.env
      - ./minio/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.type == db]
    volumes:
      - db_data:/var/lib/mysql
      - telegraf_data:/root/telegraf
    ports:
      - "3306:3306"

  httpd:
    image: 172.16.231.6:5000/httpd:0.1
    hostname: httpd
    env_file:
      - ./minio/.env
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.type == httpd]
    volumes:
      - wordpress_data:/var/www/localhost/htdocs
      - telegraf_data:/root/telegraf
    ports:
      - "80:80"

volumes:
  db_data: {}
  wordpress_data: {}
  telegraf_data: {}
  influxdb_data: {}
  kapacitor_data: {}
  chronograf_data: {}
  minio_data: {}