version: '3'

services:
  registry:
    image: registry:2
    hostname: registry
    restart: always
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 5000:5000

volumes:
  registry_data: {}