version: '3'

services:
  mysql:
    build: ./mysql
    env_file:
      - ./mysql/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.role == node01]
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build: ./wordpress
    env_file:
      - ./wordpress/.env
    volumes:
      - wordpress_data:/srv/app/wordpress

  apache:
    build: ./httpd
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '10.000'
          memory: 250M
        reservations:
          cpus: '10.000'
          memory: 220M
      placement:
        constraints: [node.role == node02]
    volumes:
      - wordpress_data:/var/www/localhost/htdocs
    ports:
      - "80:80"

volumes:
  db_data: {}
  wordpress_data: {}